config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'sessions#new'

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :user

  validates :address_line,
    :street,
    :landmark,
    :city,
    :state,
    presence: true,
    length: { minimum: 3, maximum: 25 }
  validates :pin_code, :phone_number, presence: true
  VALID_PHONE_NUMBER_REGEX = /^(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}$/i.freeze
  validates :phone_number, format: { with: VALID_PHONE_NUMBER_REGEX, multiline: true }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  has_one :address, inverse_of: :user, dependent: :destroy
  has_one_attached :avatar
  has_secure_password

  validates :username, presence: true, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, length: { maximum: 105 }
  validates :username, :email, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4})/i.freeze
  validates :email, format: { with: VALID_EMAIL_REGEX }

  scope :non_admin_users, -> { where(admin: :false) }

  accepts_nested_attributes_for :address

  before_save { self.email = email.downcase }

  # Verifies if <tt>User</tt> can edit the details.
  #
  # @param current_user [Object<User>]
  def can_edit?(current_user)
    !(self == current_user && current_user.admin?)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :require_user

  # Returns the current user logged in.
  #
  # @return [Object<User>]
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # Verifies if <tt>User</tt> is logged in.
  def logged_in?
    !!current_user
  end

  # Displays error message if the <tt>User</tt> is not logged in.
  #
  # @return [void]
  def require_user
    if !logged_in?
      flash[:danger] = 'You must be logged in to perform that action'
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  # Creates a new session for user by authenticating the password
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      create_session(user)
    else
      flash.now[:danger] = 'There was something wrong with your login information.'
      render 'new'
    end
  end

  # Destroys the user session.
  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have logged out'
    redirect_to root_path
  end

  private

  # Assigns user id as session identifier and redirects with success message.
  #
  # @param user [Object<User>]
  #
  # @return [void]
  def create_session(user)
    session[:user_id] = user.id
    flash[:success] = 'You have successfully logged in'
    redirect_to user_path(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_user, only: [:edit, :update, :index, :show]

  # Renders new form for <tt>User</tt> registration
  def new
    @user = User.new
  end

  # Renders list of non admin users.
  def index
    @users = User.non_admin_users.paginate(page: params[:page], per_page: 5)
  end

  # Creates <tt>User</tt> with parameters received.
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "User #{@user.username} registered successfully!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  # Updates <tt>User</tt> and redirects with success message.
  def update
    if @user.update(user_params)
      flash[:success] = 'Profile is successfully updated'
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private

  # Sets the <tt>User</tt> of id received in parameter
  #
  # @return [Object<User>]
  def set_user
    @user = User.find(params[:id])
  end

  # Validates if the current user is the same user whose details are being updated or is an admin.
  #
  # @return [void]
  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = 'You can only edit your own details'
      redirect_to root_path
    end
  end

  # Permitted params for <tt>User</tt>
  #
  # @return [Object<ActionController::Parameters>]
  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :avatar,
      address_attributes: [
        :address_line,
        :street,
        :landmark,
        :city,
        :state,
        :pin_code,
        :phone_number
      ]
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.haml
.row
  .col-xs-offset-1.col-xs-10
    - flash.each do |name, message|
      %div{:class => "alert alert-#{"#{name}"}"}
        %a.close{"data-dismiss" => "alert", :href => "#"} &#215;
        = content_tag :div, message, :id => "flash_#{name}" if message.is_a?(String)

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header.navbar-brand
      #logo
        = 'Profile Management'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      - if logged_in?
        %ul.nav.navbar-nav
          %li= link_to t('.general.edit_your_profile'), edit_user_path(current_user), id: 'text'
          %li= link_to t('.general.view_your_profile'), user_path(current_user), id: 'text'
          - if current_user.admin?
            .nav.navbar-nav.navbar-left
              %li= link_to t('.general.users'), users_path, id: 'text'

      %ul.nav.navbar-nav.navbar-right
        - if logged_in?
          %li= link_to t('.sessions.new.log_out'), session_path(current_user), method: :delete, id: 'text'
        - else
          %li= link_to t('.sessions.new.log_in'), new_session_path, id: 'text'
          %li= link_to t('.users.new.sign_up'), new_user_path, id: 'text'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ProfileManagement
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navigation'
    = render 'layouts/messages'
    .container
      = yield

app/views/users/_address_form.html.haml
= f.fields_for :address, @user.persisted? ? @user.address : @user.build_address do |address|
  .form-group
    .control-label.col-sm-2
      = address.label :address_line
    .col-sm-8
      = address.text_field :address_line, class: 'form-control', autofocus: true, disabled: @user.persisted? && !@user.can_edit?(current_user)
  .form-group
    .control-label.col-sm-2
      = address.label :street
    .col-sm-8
      = address.text_field :street, class: 'form-control', autofocus: true, disabled: @user.persisted? && !@user.can_edit?(current_user)
  .form-group
    .control-label.col-sm-2
      = address.label :landmark
    .col-sm-8
      = address.text_field :landmark, class: 'form-control', autofocus: true, disabled: @user.persisted? && !@user.can_edit?(current_user)
  .form-group
    .control-label.col-sm-2
      = address.label :city
    .col-sm-8
      = address.text_field :city, class: 'form-control', autofocus: true, disabled: @user.persisted? && !@user.can_edit?(current_user)
  .form-group
    .control-label.col-sm-2
      = address.label :state
    .col-sm-8
      = address.text_field :state, class: 'form-control', autofocus: true, disabled: @user.persisted? && !@user.can_edit?(current_user)
  .form-group
    .control-label.col-sm-2
      = address.label :pin_code
    .col-sm-8
      = address.text_field :pin_code, class: 'form-control', autofocus: true, disabled: @user.persisted? && !@user.can_edit?(current_user)
  .form-group
    .control-label.col-sm-2
      = address.label :phone_number
    .col-sm-8
      = address.text_field :phone_number, class: 'form-control', autofocus: true

app/views/users/_errors.html.haml
- if input.errors.any?
  .row
    .col-xs-8.col-xs-offset-2
      .panel.panel-danger
        .panel-heading
          %h2.panel-title
            = pluralize(input.errors.count, 'error') + t('general.seperator')
          .panel-body
            %ul
              - input.errors.full_messages.each do |message|
                %li= message

app/views/users/_form.html.haml
= render 'errors', input: @user
.row
  .col-xs-12
    = form_for(@user, :html => {class: 'form-horizontal', role: 'form'}) do |f|
      .form-group
        .control-label.col-sm-2
          = f.label :username
        .col-sm-8
          = f.text_field :username,
            class: 'form-control',
            placeholder: 'Enter Username',
            autofocus: true,
            disabled: logged_in? && !@user.can_edit?(current_user)
      .form-group
        .control-label.col-sm-2
          = f.label :email
        .col-sm-8
          = f.email_field :email, class: 'form-control', placeholder: 'Enter Email',
            disabled: logged_in? && !@user.can_edit?(current_user)
      .form-group
        .control-label.col-sm-2
          = f.label :password
        .col-sm-8
          = f.password_field :password, class: 'form-control', placeholder: 'Enter Password',
            disabled: logged_in? && !@user.can_edit?(current_user)
      = render 'users/address_form', f: f
      .form-group
        .control-label.col-sm-2
          = f.label :profile_picture
        .col-sm-8
          = f.file_field :avatar
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.submit(@user.new_record? ? t('users.new.sign_up') : t('users.new.update_details'), class: 'btn btn-primary btn-lg btn-xlarge')

app/views/users/edit.html.haml
%h1.center
  = t('.edit_details')
= render 'form'

app/views/users/index.html.haml
%h1.center Users
- @users.each do |user|
  .row
    .col-xs-8.col-xs-offset-2
      .well.well-lg
        .user-name
          = link_to user.username, user_path(user)
          = link_to t('.edit_this_user'), edit_user_path(user), class: 'btn btn-xs btn-primary'
%div.center
  = will_paginate @users

app/views/users/new.html.haml
%h1.center
  = t('.user_registration')
= render 'form'

app/views/users/show.html.haml
%h1.center
  = @user.username
  = t('.profile')
.row
  .col-xs-12.user-details.left
    .row
      - if @user.avatar.attached? && @user.avatar.representable?
        = image_tag url_for(@user.avatar)
    .row
      = t('.username') + t('general.seperator')
      = @user.username
    .row
      = t('.email') + t('general.seperator')
      = @user.email
    .row
      = t('.address_line') + t('general.seperator')
      = @user.address.address_line
    .row
      = t('.street') + t('general.seperator')
      = @user.address.street
    .row
      = t('.landmark') + t('general.seperator')
      = @user.address.landmark
    .row
      = t('.city') + t('general.seperator')
      = @user.address.city
    .row
      = t('.state') + t('general.seperator')
      = @user.address.state
    .row
      = t('.pin_code') + t('general.seperator')
      = @user.address.pin_code
    .row
      = t('.phone_number') + t('general.seperator')
      = @user.address.phone_number